image: mkdryden/avr-toolchain

stages:
  - build

build:
  stage: build
  script:
    - make build
  cache:
    untracked: true
    paths:
      - obj/
      - bin/
  artifacts:
    paths:
      - bin/
    expire_in: 1 week
